name: nextflow_dkl_demo_cpu
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  - numpy<2.0
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  - seaborn
  - pyyaml
  - joblib
  - hdf5
  - h5py
  - r-base
  - r-robustgasp
  - r-hdf5r
  - r-optparse
  - r-jsonlite
  - r-essentials
  - r-argparse
  - rpy2<3.6.0
  - blas=*=openblas
  - libopenblas
  - lapack
  - liblapack
  - liblapacke
  - pip
  - pip:
      - -e ./external/psimpy
      - -e ./external/gpytorch
