name: nextflow_dkl_demo_gpu
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - numpy<2.0
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  - seaborn
  - pyyaml
  - joblib
  - hdf5
  - h5py
  - r-base
  - r-robustgasp
  - r-hdf5r
  - r-optparse
  - r-jsonlite
  - r-essentials
  - r-argparse
  - pip
  - pip:
      - -e ./external/psimpy
      - -e ./external/gpytorch
